// THIS WILL LINK YOUR LOCAL REPOSITORY TO YOUR REMOTE REPOSITORY
git remote add origin https://github.com/tsola2002/html-project.git

// THIS WILL DISPLAY ALL REMOTE REPOSITORIES LINKED TO YOUR LOCAL REPOSITORY
git remote -v

// THIS PUSH OUR LOCAL REPOSITORY TO OUR REMOTE REPOSITORY
git push -u origin master

// THIS WILL PUSH ONE BRANCH TO MY REMOTE REPOSITORY
git push origin green-website


// THIS WILL PUSH ALL BRANCHES TO YOUR LOCAL GITHUB REPOSITORY
git push origin --all